name: BuddyChat
version: 0.2
main: com.github.jonnylin13.buddychat.BuddyChatPlugin
author: jlin13
commands:
  bc:
    description: -- BuddyChat by jlin13 --
    usage: /bc help
  reply:
    description: Use this to reply to a message quickly
    usage: /reply <message>
  r:
    description: Use this to reply to a message quickly
    usage: /r <message>
  whisper:
    description: Use this to send a message
    usage: /whisper <player> <message>
  w:
    description: Use this to send a message
    usage: /w <player> <message>
  cc:
    description: Use this to change channels
    usage: /cc
      